version: "3"

services:
  backend:
    container_name: pgtools-backend
    image: pgtools-backend:latest
    environment:
      - MODE=PROD
    build: ./server
    ports:
      - "5000:5000"

  frontend:
    container_name: pgtools-frontend
    image: pgtools-frontend:latest
    build: ./client
    ports:
      - "80:80"