FROM python:3.9

RUN pip install pipenv

COPY Pipfile* .

RUN pipenv lock --keep-outdated --requirements > requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD python app.py